# 입양을 간 기록은 있는데, 보호소에 들어온 기록이 없는동물
# 결과는 ANIMAL_ID 내림차순

SELECT AO.ANIMAL_ID, AO.NAME
FROM ANIMAL_INS AI RIGHT JOIN ANIMAL_OUTS AO
ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE AI.DATETIME IS NULL
ORDER BY AO.ANIMAL_ID
