-- 코드를 입력하세요
SELECT FR.PRODUCT_ID, FR.PRODUCT_NAME, SUM(FR.PRICE * FO.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT FR JOIN FOOD_ORDER FO
ON FR.PRODUCT_ID = FO.PRODUCT_ID
WHERE FO.PRODUCE_DATE LIKE "2022-05%"
GROUP BY FR.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC , FR.PRODUCT_ID ASC