-- 코드를 입력하세요
SELECT AP.APNT_NO, PA.PT_NAME, PA.PT_NO, AP.MCDP_CD, DO.DR_NAME, AP.APNT_YMD
FROM APPOINTMENT AP LEFT JOIN PATIENT PA  
ON PA.PT_NO = AP.PT_NO
LEFT JOIN DOCTOR DO
ON AP.MDDR_ID = DO.DR_ID
WHERE AP.APNT_YMD LIKE "2022-04-13%" 
AND AP.APNT_CNCL_YN LIKE "N" 
AND DO.MCDP_CD LIKE "CS"
ORDER BY AP.APNT_YMD