# 평균길이가 33CM 이상
# 10CM이 이하의 물고기들은 10CM로 고정
# 결과는 FISH_TYPE (물고기종류) 오름차순

SELECT COUNT(ID) AS FISH_COUNT, MAX(IFNULL(LENGTH, 10)) AS MAX_LENGTH, FISH_TYPE
FROM FISH_INFO
GROUP BY FISH_TYPE
HAVING AVG(IFNULL(LENGTH, 10)) >= 33
ORDER BY FISH_TYPE
